export const actionTypes = {
    USER_LOAD : "USER_LOAD",
    LOGIN: "LOGIN",
    LOG_OUT: "LOG_OUT",
    REGISTER: "REGISTER",
    GETINFOUSER: "GETINFOUSER",
    GET_DETAIL_USER: "GET_DETAIL_USER",
    GET_ALL_TEACHER: "GET_ALL_TEACHER",
    GET_DETAIL_TEACHER: "GET_DETAIL_TEACHER",
    GET_ALL_MENTOR: "GET_ALL_MENTOR",
    GET_ASSIGNMENT_STUDENT_NOT_DONE : "GET_ASSIGNMENT_STUDENT_NOT_DONE",
    GET_DETAIL_MENTOR: "GET_DETAIL_MENTOR",
    GET_ASSIGNMENT_BY_STUDENT: "GET_ASSIGNMENT_BY_STUDENT",
}